name: jancargo_app
description: Nền tảng TMĐT chuyên hàng Nhật.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+7

environment:
  sdk: '>3.1.5 <=4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  ### update
  shorebird_code_push: ^1.1.3

  ### service library connect:
  dio: any
  google_sign_in: ^6.2.1
#  flutter_facebook_auth: ^6.0.2
  connectivity_plus: ^6.0.1

  ###service
  intl: ^0.18.1
  url_launcher: ^6.2.5

  ### library processing model
  json_annotation: ^4.8.1
  injectable: ^2.3.2
  json_model: ^1.0.0

  ### library noti and alert,toast:
  alert_banner: ^1.0.0
  fluttertoast: ^8.2.2
  logger: ^2.0.1


  ### library permission:
  permission_handler: ^11.0.1

  ### library logic:
  equatable: ^2.0.5
  either_dart: ^1.0.0
  flutter_bloc: ^8.1.2

  ### library material app:
  flutter_screenutil: ^5.9.0
  flutter_statusbarcolor_ns: ^0.5.0

  ### library widget auth:
  email_validator: ^2.0.1
  dotted_border: ^2.0.0+3
  auto_size_text: ^3.0.0
  diacritic: ^0.1.3

  ### storage
  hive: ^2.2.3
  path_provider: ^2.1.1

  ### Image
  flutter_svg: ^2.0.9

  ###
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.12.1
  webview_flutter_wkwebview: ^3.9.3
  flutter_spinkit: ^5.2.0

  ###firebase
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  firebase_analytics: ^10.4.3
  firebase_messaging: ^14.7.3
  flutter_local_notifications: ^17.0.0
  universal_html: ^2.2.4
  g_recaptcha_v3: ^0.0.5

  ###Widget
  pinput: ^4.0.0
  loading_animation_widget: ^1.2.0+4
  loading_indicator: ^3.1.1
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.0
  pull_to_refresh: ^2.0.0
  expand_widget: ^3.1.1
  remixicon: ^1.0.0
  persistent_bottom_nav_bar: ^5.0.2
  modal_bottom_sheet: ^3.0.0-pre
  sliver_tools: ^0.2.12
  slivers: ^0.0.1+2
  visibility_detector: ^0.4.0+2
  currency_text_input_formatter: ^2.1.8
  add_to_cart_animation: ^2.0.3
  scrollable_positioned_list: ^0.3.8
  dropdown_textfield: ^1.0.8
  animated_search_bar: ^2.7.1
  easy_debounce: ^2.0.3
  flutter_html: ^3.0.0-beta.2
  el_tooltip: ^2.0.0

  ### shared_preferences:
  share_plus: ^8.0.2
  flutter_share_me: ^1.4.0


dev_dependencies:
#  flutter_test:
#    sdk: flutter

  # flutter pub run build_runner build
  # or
  # or
  # flutter pub run build_runner build --delete-conflicting-outputs
  #flutter packages pub run build_runner build
  build_runner: ^2.4.6
  injectable_generator: ^2.1.5
  json_serializable: ^6.7.1



  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.2
  flutter_launcher_icons: 0.13.1


flutter_launcher_icons:
  image_path: "assets/png/icon.png"
#  image_path_android: "assets/png/icon.png"
#  image_path_ios: "assets/png/icon.png"
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21
  image_path_ios: "assets/png/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/png/
    - assets/icon/
    - assets/svg/
    - assets/fonts/
    - shorebird.yaml

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: K2D
      fonts:
        - asset: assets/fonts/K2D-Regular.ttf
          weight: 400
        - asset: assets/fonts/K2D-Medium.ttf
          weight: 500
        - asset: assets/fonts/K2D-Bold.ttf
          weight: 700


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
